compile:
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang A3.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang C2.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang D3.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang E1.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang A4.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang C3.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang D5.c -O2 -c -o /dev/null
	~/Downloads/clang+llvm-10.0-1.0-x86_64-apple-darwin/bin/clang report-example.c -O2 -c -o /dev/null
